---
- name: Collect memory usage (sar)
  shell: |
    sar -r -f /var/log/sysstat/sa$(date +%d) | tail -n +4
  register: mem_sar
  changed_when: false

- set_fact:
    memory_usage: "{{ mem_sar.stdout_lines }}"
